name: posegen
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - tqdm
  - cudatoolkit=11.1
  - torchvision
  - pytorch
  - tensorboard
  - scipy
  - torchmetrics
  - pandas
  - pillow
  - pip:
    - torch-fidelity
    - wandb
    - mmh3
